import { Cake, Product } from "./definitions";

export const products: Product[] = [
    {
        id: "1",
        title: "Torniquetes de Almendra",
        descrition:"Torniquetes hechos con masa de hojaldre cubiertos con hilos de glaseado y almendras.",
        price:4.00,
        stock: 20,
    },
    {
        id: "2",
        title: "Tartaleta de caramelo y nueces",
        descrition:"Tartaleta rellena de chessecake cubierta con caramelo hecho en casa y nueces.",
        price:12.0,
        stock: 2,
    },
    {
        id: "3",
        title: "Croissant de Mantequilla",
        descrition:"Croissant clásico de mantequilla ideal para comerlo con mermelada u otras jaleas o para sandwiches.",
        price:5.5,
        stock: 2,
    },
    {
        id: "4",
        title: "Tartaleta de caramelo y nueces",
        descrition:"Tartaleta rellena de chessecake cubierta con caramelo hecho en casa y nueces.",
        price:12.0,
        stock: 2,
    },
    {
        id: "5",
        title: "Tartaleta de caramelo y nueces",
        descrition:"Tartaleta rellena de chessecake cubierta con caramelo hecho en casa y nueces.",
        price:12.0,
        stock: 2,
    },
    {
        id: "6",
        title: "Tartaleta de caramelo y nueces",
        descrition:"Tartaleta rellena de chessecake cubierta con caramelo hecho en casa y nueces.",
        price:12.0,
        stock: 2,
    },
    {
        id: "7",
        title: "Tartaleta de caramelo y nueces",
        descrition:"Tartaleta rellena de chessecake cubierta con caramelo hecho en casa y nueces.",
        price:12.0,
        stock: 2,
    },
    {
        id: "8",
        title: "Tartaleta de caramelo y nueces",
        descrition:"Tartaleta rellena de chessecake cubierta con caramelo hecho en casa y nueces.",
        price:12.0,
        stock: 2,
    }
]

export const cakes: Cake[] = [
    {
        id: "1",
        title: "Torta de tres leches",
        description:"Torta tres leches con relleno de dulce de leche.",
        price_1:150.0,
        price_2:260.0,
        price_3:400.0,
        price_4:540.0,
    },
    {
        id: "2",
        title: "Torta de coco",
        description:"Masa de coco rayado natural rellena con crema pastelera de vainilla. Cubierta con crema de leche y coco rayado.",
        price_1:150.0,
        price_2:260.0,
        price_3:400.0,
        price_4:540.0,
    },
    {
        id: "3",
        title: "Torta de limón",
        description:"Torta rellena con pie de limón y cubierta de merengue.",
        price_1:150.0,
        price_2:260.0,
        price_3:400.0,
        price_4:540.0,
    },
    {
        id: "4",
        title: "Torta de maracuyá y merengue",
        description:"orta rellena con crema de maracuya y cubierta con jalea de maracuyá y merengue suizo.",
        price_1:150.0,
        price_2:260.0,
        price_3:400.0,
        price_4:540.0,
    },
    {
        id: "5",
        title: "Torta de chocolate con crema",
        description:"Torta de chocolate con relleno de dulce de leche y cobertura de crema de leche batida.",
        price_1:150.0,
        price_2:260.0,
        price_3:400.0,
        price_4:540.0,
    },
    {
        id: "6",
        title: "Torta de choconut",
        description:"Torta de chocolate con relleno de dulce de leche, almendras y maní picados, cobertura de crema de leche y ganash de chocolate.",
        price_1:150.0,
        price_2:260.0,
        price_3:400.0,
        price_4:540.0,
    },
    {
        id: "7",
        title: "Torta de chocomaracuyá",
        description:"Torta de chocomaracuyá hecha con cocoa orgánica y crema de maracuyá hecha con la fruta natural.",
        price_1:150.0,
        price_2:260.0,
        price_3:400.0,
        price_4:540.0,
    },
    {
        id: "8",
        title: "Torta megachocolate",
        description:"Torta de chocolate, rellena con manjar de dulce de leche y cubierta con buttercream de chocolate semiamargo.",
        price_1:150.0,
        price_2:260.0,
        price_3:400.0,
        price_4:540.0,
    },
]